### ISSUE TITLE
Please officially add Teensy 4.0 and 4.1 support

### ISSUE THREAD

**Issue by mdluffy1234** [SantiagoSaldana/SBC#1]
Recently, the ArduinoXInput_Teensy library added Teensy 4.0 and 4.1 support, and I wanted to ask if you could adapt the SBC library to work with them as well. Also, could you please update the instructions on Hackaday to reflect these new developments?

**Comment by SantiagoSaldana** [comment]
@mdluffy1234 
I spent several hours getting this to work today.

Good News!  Nothing has to be done to the library at all, you just need to install the latest version of Teensy.

Just copy over the new Xinput files:
https://github.com/dmadison/ArduinoXInput_Teensy/releases/tag/v1.1.1

And then in Arduino go to Tools->Manage Libraries
in the Library Manager select Xinput and click Update, you should be at version 1.2.6

I suggest testing it with the HIDjoystick example and follow the hackaday instructions to test.

WARNING!!!
what took me forever tonight to figure out was that my XBox->USB adapter was not making proper connection.  I may end up replacing the entire USB cable to go straight to USB as I have never owned an original XBOX.  I had to push on it with my thumb to make sure the connection was good.

**Comment by mdluffy1234** [comment]
could you please update the Hackaday site with these findings? That way it'll be easier for new ppl who find this project to make it with a 4.1?

**Comment by SantiagoSaldana** [comment]
I updated the site as well.  Thanks for bringing all this to my attention.
